// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file auth.proto (package auth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth.proto.
 */
export const file_auth: GenFile = /*@__PURE__*/
  fileDesc("CgphdXRoLnByb3RvEgRhdXRoIkQKD1JlZ2lzdGVyUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCgh1c2VybmFtZRgCIAEoCRIQCghwYXNzd29yZBgDIAEoCSI0ChBSZWdpc3RlclJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCSIvCgxMb2dpblJlcXVlc3QSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkibQoNTG9naW5SZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEh4KB2FjY291bnQYAiABKAsyDS5hdXRoLkFjY291bnQSFAoMYWNjZXNzX3Rva2VuGAMgASgJEhUKDXJlZnJlc2hfdG9rZW4YBCABKAkiLAoTUmVmcmVzaFRva2VuUmVxdWVzdBIVCg1yZWZyZXNoX3Rva2VuGAEgASgJIlQKFFJlZnJlc2hUb2tlblJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSFAoMYWNjZXNzX3Rva2VuGAIgASgJEhUKDXJlZnJlc2hfdG9rZW4YAyABKAkiDwoNTG9nb3V0UmVxdWVzdCIhCg5Mb2dvdXRSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIgsKCU1lUmVxdWVzdCIsCgpNZVJlc3BvbnNlEh4KB2FjY291bnQYASABKAsyDS5hdXRoLkFjY291bnQiSgoHQWNjb3VudBIKCgJpZBgBIAEoCRINCgVlbWFpbBgCIAEoCRIQCgh1c2VybmFtZRgDIAEoCRISCgpjcmVhdGVkX2F0GAQgASgJMp8CCgtBdXRoU2VydmljZRI5CghSZWdpc3RlchIVLmF1dGguUmVnaXN0ZXJSZXF1ZXN0GhYuYXV0aC5SZWdpc3RlclJlc3BvbnNlEjAKBUxvZ2luEhIuYXV0aC5Mb2dpblJlcXVlc3QaEy5hdXRoLkxvZ2luUmVzcG9uc2USRQoMUmVmcmVzaFRva2VuEhkuYXV0aC5SZWZyZXNoVG9rZW5SZXF1ZXN0GhouYXV0aC5SZWZyZXNoVG9rZW5SZXNwb25zZRIzCgZMb2dvdXQSEy5hdXRoLkxvZ291dFJlcXVlc3QaFC5hdXRoLkxvZ291dFJlc3BvbnNlEicKAk1lEg8uYXV0aC5NZVJlcXVlc3QaEC5hdXRoLk1lUmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message auth.RegisterRequest
 */
export type RegisterRequest = Message<"auth.RegisterRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * Added username to match accounts table
   *
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message auth.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_auth, 0);

/**
 * @generated from message auth.RegisterResponse
 */
export type RegisterResponse = Message<"auth.RegisterResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message auth.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_auth, 1);

/**
 * @generated from message auth.LoginRequest
 */
export type LoginRequest = Message<"auth.LoginRequest"> & {
  /**
   * Can be email or username logic-wise, but field name implies email
   *
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_auth, 2);

/**
 * @generated from message auth.LoginResponse
 */
export type LoginResponse = Message<"auth.LoginResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: auth.Account account = 2;
   */
  account?: Account;

  /**
   * @generated from field: string access_token = 3;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 4;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_auth, 3);

/**
 * @generated from message auth.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"auth.RefreshTokenRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/
  messageDesc(file_auth, 4);

/**
 * @generated from message auth.RefreshTokenResponse
 */
export type RefreshTokenResponse = Message<"auth.RefreshTokenResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * Optional: rotate refresh token
   *
   * @generated from field: string refresh_token = 3;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse> = /*@__PURE__*/
  messageDesc(file_auth, 5);

/**
 * @generated from message auth.LogoutRequest
 */
export type LogoutRequest = Message<"auth.LogoutRequest"> & {
};

/**
 * Describes the message auth.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_auth, 6);

/**
 * @generated from message auth.LogoutResponse
 */
export type LogoutResponse = Message<"auth.LogoutResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message auth.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_auth, 7);

/**
 * @generated from message auth.MeRequest
 */
export type MeRequest = Message<"auth.MeRequest"> & {
};

/**
 * Describes the message auth.MeRequest.
 * Use `create(MeRequestSchema)` to create a new message.
 */
export const MeRequestSchema: GenMessage<MeRequest> = /*@__PURE__*/
  messageDesc(file_auth, 8);

/**
 * @generated from message auth.MeResponse
 */
export type MeResponse = Message<"auth.MeResponse"> & {
  /**
   * @generated from field: auth.Account account = 1;
   */
  account?: Account;
};

/**
 * Describes the message auth.MeResponse.
 * Use `create(MeResponseSchema)` to create a new message.
 */
export const MeResponseSchema: GenMessage<MeResponse> = /*@__PURE__*/
  messageDesc(file_auth, 9);

/**
 * @generated from message auth.Account
 */
export type Account = Message<"auth.Account"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * Added username
   *
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: string created_at = 4;
   */
  createdAt: string;
};

/**
 * Describes the message auth.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema: GenMessage<Account> = /*@__PURE__*/
  messageDesc(file_auth, 10);

/**
 * AuthService handles user registration, authentication, and session management.
 *
 * @generated from service auth.AuthService
 */
export const AuthService: GenService<{
  /**
   * Register a new user.
   *
   * @generated from rpc auth.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * Log in an existing user.
   *
   * @generated from rpc auth.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * Refresh the access token using a refresh token.
   *
   * @generated from rpc auth.AuthService.RefreshToken
   */
  refreshToken: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof RefreshTokenResponseSchema;
  },
  /**
   * Log out the current user.
   *
   * @generated from rpc auth.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
  /**
   * Get the current authenticated user's profile.
   *
   * @generated from rpc auth.AuthService.Me
   */
  me: {
    methodKind: "unary";
    input: typeof MeRequestSchema;
    output: typeof MeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth, 0);

