// @generated by protoc-gen-es v2.10.1 with parameter "target=ts"
// @generated from file auth.proto (package auth, syntax proto3)
/* eslint-disable */
import type { Message } from '@bufbuild/protobuf';
import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv2';

/**
 * Describes the file auth.proto.
 */
export const file_auth: GenFile =
  /*@__PURE__*/
  fileDesc(
    'CgphdXRoLnByb3RvEgRhdXRoIkQKD1JlZ2lzdGVyUmVxdWVzdBINCgVlbWFpbBgBIAEoCRIQCgh1c2VybmFtZRgCIAEoCRIQCghwYXNzd29yZBgDIAEoCSI0ChBSZWdpc3RlclJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCSIvCgxMb2dpblJlcXVlc3QSDQoFZW1haWwYASABKAkSEAoIcGFzc3dvcmQYAiABKAkibQoNTG9naW5SZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIEh4KB2FjY291bnQYAiABKAsyDS5hdXRoLkFjY291bnQSFAoMYWNjZXNzX3Rva2VuGAMgASgJEhUKDXJlZnJlc2hfdG9rZW4YBCABKAkiPgoTUmVmcmVzaFRva2VuUmVxdWVzdBIVCg1yZWZyZXNoX3Rva2VuGAEgASgJEhAKCHJlYWxtX2lkGAIgASgJIlQKFFJlZnJlc2hUb2tlblJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSFAoMYWNjZXNzX3Rva2VuGAIgASgJEhUKDXJlZnJlc2hfdG9rZW4YAyABKAkiDwoNTG9nb3V0UmVxdWVzdCIhCg5Mb2dvdXRSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIgsKCU1lUmVxdWVzdCIsCgpNZVJlc3BvbnNlEh4KB2FjY291bnQYASABKAsyDS5hdXRoLkFjY291bnQiSgoHQWNjb3VudBIKCgJpZBgBIAEoCRINCgVlbWFpbBgCIAEoCRIQCgh1c2VybmFtZRgDIAEoCRISCgpjcmVhdGVkX2F0GAQgASgJIhMKEUxpc3RSZWFsbXNSZXF1ZXN0IjEKEkxpc3RSZWFsbXNSZXNwb25zZRIbCgZyZWFsbXMYASADKAsyCy5hdXRoLlJlYWxtInMKBVJlYWxtEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSFAoMZGlzcGxheV9uYW1lGAMgASgJEhMKC2Rlc2NyaXB0aW9uGAQgASgJEhEKCWlzX2FjdGl2ZRgFIAEoCBISCgpjcmVhdGVkX2F0GAYgASgJIk0KEkNyZWF0ZVJlYWxtUmVxdWVzdBIMCgRuYW1lGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCSJTChNDcmVhdGVSZWFsbVJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgSDwoHbWVzc2FnZRgCIAEoCRIaCgVyZWFsbRgDIAEoCzILLmF1dGguUmVhbG0ypAMKC0F1dGhTZXJ2aWNlEjkKCFJlZ2lzdGVyEhUuYXV0aC5SZWdpc3RlclJlcXVlc3QaFi5hdXRoLlJlZ2lzdGVyUmVzcG9uc2USMAoFTG9naW4SEi5hdXRoLkxvZ2luUmVxdWVzdBoTLmF1dGguTG9naW5SZXNwb25zZRJFCgxSZWZyZXNoVG9rZW4SGS5hdXRoLlJlZnJlc2hUb2tlblJlcXVlc3QaGi5hdXRoLlJlZnJlc2hUb2tlblJlc3BvbnNlEjMKBkxvZ291dBITLmF1dGguTG9nb3V0UmVxdWVzdBoULmF1dGguTG9nb3V0UmVzcG9uc2USJwoCTWUSDy5hdXRoLk1lUmVxdWVzdBoQLmF1dGguTWVSZXNwb25zZRI/CgpMaXN0UmVhbG1zEhcuYXV0aC5MaXN0UmVhbG1zUmVxdWVzdBoYLmF1dGguTGlzdFJlYWxtc1Jlc3BvbnNlEkIKC0NyZWF0ZVJlYWxtEhguYXV0aC5DcmVhdGVSZWFsbVJlcXVlc3QaGS5hdXRoLkNyZWF0ZVJlYWxtUmVzcG9uc2ViBnByb3RvMw',
  );

/**
 * @generated from message auth.RegisterRequest
 */
export type RegisterRequest = Message<'auth.RegisterRequest'> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * Added username to match accounts table
   *
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message auth.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/ messageDesc(file_auth, 0);

/**
 * @generated from message auth.RegisterResponse
 */
export type RegisterResponse = Message<'auth.RegisterResponse'> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message auth.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/ messageDesc(file_auth, 1);

/**
 * @generated from message auth.LoginRequest
 */
export type LoginRequest = Message<'auth.LoginRequest'> & {
  /**
   * Can be email or username logic-wise, but field name implies email
   *
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/ messageDesc(file_auth, 2);

/**
 * @generated from message auth.LoginResponse
 */
export type LoginResponse = Message<'auth.LoginResponse'> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: auth.Account account = 2;
   */
  account?: Account;

  /**
   * @generated from field: string access_token = 3;
   */
  accessToken: string;

  /**
   * @generated from field: string refresh_token = 4;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/ messageDesc(file_auth, 3);

/**
 * @generated from message auth.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<'auth.RefreshTokenRequest'> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;

  /**
   * Optional: realm ID to include in JWT token
   *
   * @generated from field: string realm_id = 2;
   */
  realmId: string;
};

/**
 * Describes the message auth.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/ messageDesc(file_auth, 4);

/**
 * @generated from message auth.RefreshTokenResponse
 */
export type RefreshTokenResponse = Message<'auth.RefreshTokenResponse'> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string access_token = 2;
   */
  accessToken: string;

  /**
   * Optional: rotate refresh token
   *
   * @generated from field: string refresh_token = 3;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse> = /*@__PURE__*/ messageDesc(file_auth, 5);

/**
 * @generated from message auth.LogoutRequest
 */
export type LogoutRequest = Message<'auth.LogoutRequest'> & {};

/**
 * Describes the message auth.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/ messageDesc(file_auth, 6);

/**
 * @generated from message auth.LogoutResponse
 */
export type LogoutResponse = Message<'auth.LogoutResponse'> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message auth.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/ messageDesc(file_auth, 7);

/**
 * @generated from message auth.MeRequest
 */
export type MeRequest = Message<'auth.MeRequest'> & {};

/**
 * Describes the message auth.MeRequest.
 * Use `create(MeRequestSchema)` to create a new message.
 */
export const MeRequestSchema: GenMessage<MeRequest> = /*@__PURE__*/ messageDesc(file_auth, 8);

/**
 * @generated from message auth.MeResponse
 */
export type MeResponse = Message<'auth.MeResponse'> & {
  /**
   * @generated from field: auth.Account account = 1;
   */
  account?: Account;
};

/**
 * Describes the message auth.MeResponse.
 * Use `create(MeResponseSchema)` to create a new message.
 */
export const MeResponseSchema: GenMessage<MeResponse> = /*@__PURE__*/ messageDesc(file_auth, 9);

/**
 * @generated from message auth.Account
 */
export type Account = Message<'auth.Account'> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * Added username
   *
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: string created_at = 4;
   */
  createdAt: string;
};

/**
 * Describes the message auth.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema: GenMessage<Account> = /*@__PURE__*/ messageDesc(file_auth, 10);

/**
 * @generated from message auth.ListRealmsRequest
 */
export type ListRealmsRequest = Message<'auth.ListRealmsRequest'> & {};

/**
 * Describes the message auth.ListRealmsRequest.
 * Use `create(ListRealmsRequestSchema)` to create a new message.
 */
export const ListRealmsRequestSchema: GenMessage<ListRealmsRequest> = /*@__PURE__*/ messageDesc(file_auth, 11);

/**
 * @generated from message auth.ListRealmsResponse
 */
export type ListRealmsResponse = Message<'auth.ListRealmsResponse'> & {
  /**
   * @generated from field: repeated auth.Realm realms = 1;
   */
  realms: Realm[];
};

/**
 * Describes the message auth.ListRealmsResponse.
 * Use `create(ListRealmsResponseSchema)` to create a new message.
 */
export const ListRealmsResponseSchema: GenMessage<ListRealmsResponse> = /*@__PURE__*/ messageDesc(file_auth, 12);

/**
 * @generated from message auth.Realm
 */
export type Realm = Message<'auth.Realm'> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * Optional
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: bool is_active = 5;
   */
  isActive: boolean;

  /**
   * @generated from field: string created_at = 6;
   */
  createdAt: string;
};

/**
 * Describes the message auth.Realm.
 * Use `create(RealmSchema)` to create a new message.
 */
export const RealmSchema: GenMessage<Realm> = /*@__PURE__*/ messageDesc(file_auth, 13);

/**
 * @generated from message auth.CreateRealmRequest
 */
export type CreateRealmRequest = Message<'auth.CreateRealmRequest'> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Optional
   *
   * @generated from field: string description = 3;
   */
  description: string;
};

/**
 * Describes the message auth.CreateRealmRequest.
 * Use `create(CreateRealmRequestSchema)` to create a new message.
 */
export const CreateRealmRequestSchema: GenMessage<CreateRealmRequest> = /*@__PURE__*/ messageDesc(file_auth, 14);

/**
 * @generated from message auth.CreateRealmResponse
 */
export type CreateRealmResponse = Message<'auth.CreateRealmResponse'> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: auth.Realm realm = 3;
   */
  realm?: Realm;
};

/**
 * Describes the message auth.CreateRealmResponse.
 * Use `create(CreateRealmResponseSchema)` to create a new message.
 */
export const CreateRealmResponseSchema: GenMessage<CreateRealmResponse> = /*@__PURE__*/ messageDesc(file_auth, 15);

/**
 * AuthService handles user registration, authentication, and session management.
 *
 * @generated from service auth.AuthService
 */
export const AuthService: GenService<{
  /**
   * Register a new user.
   *
   * @generated from rpc auth.AuthService.Register
   */
  register: {
    methodKind: 'unary';
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  };
  /**
   * Log in an existing user.
   *
   * @generated from rpc auth.AuthService.Login
   */
  login: {
    methodKind: 'unary';
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  };
  /**
   * Refresh the access token using a refresh token.
   *
   * @generated from rpc auth.AuthService.RefreshToken
   */
  refreshToken: {
    methodKind: 'unary';
    input: typeof RefreshTokenRequestSchema;
    output: typeof RefreshTokenResponseSchema;
  };
  /**
   * Log out the current user.
   *
   * @generated from rpc auth.AuthService.Logout
   */
  logout: {
    methodKind: 'unary';
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  };
  /**
   * Get the current authenticated user's profile.
   *
   * @generated from rpc auth.AuthService.Me
   */
  me: {
    methodKind: 'unary';
    input: typeof MeRequestSchema;
    output: typeof MeResponseSchema;
  };
  /**
   * List realms accessible to the authenticated user.
   *
   * @generated from rpc auth.AuthService.ListRealms
   */
  listRealms: {
    methodKind: 'unary';
    input: typeof ListRealmsRequestSchema;
    output: typeof ListRealmsResponseSchema;
  };
  /**
   * Create a new realm and assign the creator as admin.
   *
   * @generated from rpc auth.AuthService.CreateRealm
   */
  createRealm: {
    methodKind: 'unary';
    input: typeof CreateRealmRequestSchema;
    output: typeof CreateRealmResponseSchema;
  };
}> = /*@__PURE__*/ serviceDesc(file_auth, 0);
