// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file hello.proto (package hello, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file hello.proto.
 */
export const file_hello: GenFile = /*@__PURE__*/
  fileDesc("CgtoZWxsby5wcm90bxIFaGVsbG8iKgoMSGVsbG9SZXF1ZXN0EhEKBG5hbWUYASABKAlIAIgBAUIHCgVfbmFtZSIgCg1IZWxsb1Jlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkyjQEKEUhlbGxvV29ybGRTZXJ2aWNlEjcKCFNheUhlbGxvEhMuaGVsbG8uSGVsbG9SZXF1ZXN0GhQuaGVsbG8uSGVsbG9SZXNwb25zZSIAEj8KDlNheUhlbGxvU3RyZWFtEhMuaGVsbG8uSGVsbG9SZXF1ZXN0GhQuaGVsbG8uSGVsbG9SZXNwb25zZSIAMAFiBnByb3RvMw");

/**
 * @generated from message hello.HelloRequest
 */
export type HelloRequest = Message<"hello.HelloRequest"> & {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string;
};

/**
 * Describes the message hello.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export const HelloRequestSchema: GenMessage<HelloRequest> = /*@__PURE__*/
  messageDesc(file_hello, 0);

/**
 * @generated from message hello.HelloResponse
 */
export type HelloResponse = Message<"hello.HelloResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message hello.HelloResponse.
 * Use `create(HelloResponseSchema)` to create a new message.
 */
export const HelloResponseSchema: GenMessage<HelloResponse> = /*@__PURE__*/
  messageDesc(file_hello, 1);

/**
 * @generated from service hello.HelloWorldService
 */
export const HelloWorldService: GenService<{
  /**
   * @generated from rpc hello.HelloWorldService.SayHello
   */
  sayHello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloResponseSchema;
  },
  /**
   * @generated from rpc hello.HelloWorldService.SayHelloStream
   */
  sayHelloStream: {
    methodKind: "server_streaming";
    input: typeof HelloRequestSchema;
    output: typeof HelloResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_hello, 0);

