import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';

import { RpcClientProvider } from '@workspace/rpc-client';
import '@workspace/ui/globals.css';

import { Providers } from '@/components/providers';

const fontSans = Geist({
  subsets: ['latin'],
  variable: '--font-sans',
});

const fontMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased`}>
        <RpcClientProvider>
          <Providers>{children}</Providers>
        </RpcClientProvider>
      </body>
    </html>
  );
}
