//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "account_realm_roles")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub realm_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: Uuid,
    pub granted_at: DateTimeWithTimeZone,
    pub granted_by: Option<Uuid>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Accounts2",
        from = "account_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub accounts_2: HasOne<super::accounts::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Accounts1",
        from = "granted_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub accounts_1: HasOne<super::accounts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "realm_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub realms: HasOne<super::realms::Entity>,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub roles: HasOne<super::roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
