//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "accounts")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text", unique)]
    pub email: String,
    pub email_verified: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub password_hash: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::federated_identities::Entity")]
    FederatedIdentities,
    #[sea_orm(has_many = "super::realms::Entity")]
    Realms,
}

impl Related<super::federated_identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FederatedIdentities.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::identity_providers::Entity> for Entity {
    fn to() -> RelationDef {
        super::federated_identities::Relation::IdentityProviders.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::federated_identities::Relation::Accounts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
