//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "bots")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(nullable)]
    pub api_channel_bridge_id: Option<Uuid>,
    #[sea_orm(nullable)]
    pub oauth_channel_bridge_id: Option<Uuid>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(nullable)]
    pub capabilities: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channel_bridge::Entity",
        from = "Column::ApiChannelBridgeId",
        to = "super::channel_bridge::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChannelBridge2,
    #[sea_orm(
        belongs_to = "super::channel_bridge::Entity",
        from = "Column::OauthChannelBridgeId",
        to = "super::channel_bridge::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ChannelBridge1,
}

impl ActiveModelBehavior for ActiveModel {}
