//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "bots")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub realm_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(nullable)]
    pub api_channel_bridge_id: Option<Uuid>,
    #[sea_orm(nullable)]
    pub oauth_channel_bridge_id: Option<Uuid>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(nullable)]
    pub capabilities: Option<Vec<String>>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ChannelBridge2",
        from = "api_channel_bridge_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub channel_bridge_2: HasOne<super::channel_bridge::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "ChannelBridge1",
        from = "oauth_channel_bridge_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub channel_bridge_1: HasOne<super::channel_bridge::Entity>,
    #[sea_orm(
        belongs_to,
        from = "realm_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub realms: HasOne<super::realms::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
