//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "chats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub trip_id: Option<Uuid>,
    pub created_by: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub is_main: bool,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_participants::Entity")]
    ChatParticipants,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
    #[sea_orm(
        belongs_to = "super::profiles::Entity",
        from = "Column::CreatedBy",
        to = "super::profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Profiles,
    #[sea_orm(
        belongs_to = "super::trips::Entity",
        from = "Column::TripId",
        to = "super::trips::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Trips,
}

impl Related<super::chat_participants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatParticipants.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::trips::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trips.def()
    }
}

impl Related<super::profiles::Entity> for Entity {
    fn to() -> RelationDef {
        super::chat_participants::Relation::Profiles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::chat_participants::Relation::Chats.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
