//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "chat_participants")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub chat_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub profile_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    pub joined_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "chat_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub chats: HasOne<super::chats::Entity>,
    #[sea_orm(
        belongs_to,
        from = "profile_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub profiles: HasOne<super::profiles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
