//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "chats")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub trip_id: Option<Uuid>,
    pub created_by: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    pub is_main: bool,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(has_many)]
    pub messages: HasMany<super::messages::Entity>,
    #[sea_orm(
        belongs_to,
        from = "trip_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub trips: HasOne<super::trips::Entity>,
    #[sea_orm(has_many, via = "chat_participants")]
    pub profiles: HasMany<super::profiles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
