//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "federated_identities")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: Uuid,
    #[sea_orm(
        primary_key,
        auto_increment = false,
        unique_key = "uq_federated_identities_provider_user"
    )]
    pub identity_provider_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "uq_federated_identities_provider_user"
    )]
    pub external_user_id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub external_username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub access_token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub refresh_token: Option<String>,
    pub token_expiry: Option<DateTimeWithTimeZone>,
    pub first_login_at: DateTimeWithTimeZone,
    pub last_login_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(
        belongs_to,
        from = "account_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub accounts: HasOne<super::accounts::Entity>,
    #[sea_orm(
        belongs_to,
        from = "identity_provider_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub identity_providers: HasOne<super::identity_providers::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
