//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_providers")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_identity_providers_realm_alias")]
    pub realm_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub provider_type: String,
    #[sea_orm(column_type = "Text", unique_key = "uq_identity_providers_realm_alias")]
    pub alias: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    pub is_enabled: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_secret: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub authorization_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub token_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_info_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_entity_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_sso_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_certificate: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub default_scopes: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::federated_identities::Entity")]
    FederatedIdentities,
    #[sea_orm(
        belongs_to = "super::realms::Entity",
        from = "Column::RealmId",
        to = "super::realms::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Realms,
}

impl Related<super::federated_identities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FederatedIdentities.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::accounts::Entity> for Entity {
    fn to() -> RelationDef {
        super::federated_identities::Relation::Accounts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::federated_identities::Relation::IdentityProviders
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
