//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identity_providers")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_identity_providers_realm_alias")]
    pub realm_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub provider_type: String,
    #[sea_orm(column_type = "Text", unique_key = "uq_identity_providers_realm_alias")]
    pub alias: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    pub is_enabled: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub client_secret: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub authorization_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub token_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub user_info_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_entity_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_sso_url: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub saml_certificate: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub default_scopes: Option<Vec<String>>,
    #[sea_orm(
        belongs_to,
        from = "realm_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub realms: HasOne<super::realms::Entity>,
    #[sea_orm(has_many, via = "federated_identities")]
    pub accounts: HasMany<super::accounts::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
