//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub mod prelude;

pub mod bots;
pub mod channel_bridge;
pub mod chat_participants;
pub mod chats;
pub mod messages;
pub mod profiles;
pub mod spatial_ref_sys;
pub mod trip_card_rich_text;
pub mod trip_card_votes;
pub mod trip_cards;
pub mod trip_participants;
pub mod trips;
