//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "messages")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        unique_key = "messages_id_created_at_key"
    )]
    pub id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub chat_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub sender_role: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    #[sea_orm(
        primary_key,
        auto_increment = false,
        unique_key = "messages_id_created_at_key"
    )]
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(
        belongs_to,
        from = "chat_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub chats: HasOne<super::chats::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
