//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "permissions")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_permissions_realm_role_resource")]
    pub realm_id: Uuid,
    #[sea_orm(unique_key = "uq_permissions_realm_role_resource")]
    pub role_id: Uuid,
    #[sea_orm(
        column_type = "Text",
        unique_key = "uq_permissions_realm_role_resource"
    )]
    pub resource_type: String,
    pub created_at: DateTimeWithTimeZone,
    pub actions: Vec<String>,
    #[sea_orm(
        belongs_to,
        from = "realm_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub realms: HasOne<super::realms::Entity>,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub roles: HasOne<super::roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
