//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.17

pub use super::conversations::Entity as Conversations;
pub use super::messages::Entity as Messages;
pub use super::users::Entity as Users;
