//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "profiles")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "idx_profiles_third_login")]
    pub realm_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub phone: String,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "idx_profiles_third_login"
    )]
    pub third_id: Option<String>,
    #[sea_orm(
        column_type = "Text",
        nullable,
        unique_key = "idx_profiles_third_login"
    )]
    pub third_provider_type: Option<String>,
    pub channel_bridge_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(
        belongs_to,
        from = "channel_bridge_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub channel_bridge: HasOne<super::channel_bridge::Entity>,
    #[sea_orm(
        belongs_to,
        from = "realm_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub realms: HasOne<super::realms::Entity>,
    #[sea_orm(has_many)]
    pub trip_card_rich_texts: HasMany<super::trip_card_rich_text::Entity>,
    #[sea_orm(has_many, via = "chat_participants")]
    pub chats: HasMany<super::chats::Entity>,
    #[sea_orm(has_many, via = "trip_card_votes")]
    pub trip_cards: HasMany<super::trip_cards::Entity>,
    #[sea_orm(has_many, via = "trip_participants")]
    pub trips: HasMany<super::trips::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
