//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "realms")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(has_many)]
    pub account_realm_roles: HasMany<super::account_realm_roles::Entity>,
    #[sea_orm(has_many)]
    pub bots: HasMany<super::bots::Entity>,
    #[sea_orm(has_many)]
    pub identity_providers: HasMany<super::identity_providers::Entity>,
    #[sea_orm(has_many)]
    pub permissions: HasMany<super::permissions::Entity>,
    #[sea_orm(has_many)]
    pub profiles: HasMany<super::profiles::Entity>,
    #[sea_orm(has_many)]
    pub roles: HasMany<super::roles::Entity>,
    #[sea_orm(has_many)]
    pub trips: HasMany<super::trips::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
