//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "roles")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_roles_realm_name")]
    pub realm_id: Uuid,
    #[sea_orm(column_type = "Text", unique_key = "uq_roles_realm_name")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub account_realm_roles: HasMany<super::account_realm_roles::Entity>,
    #[sea_orm(has_many)]
    pub permissions: HasMany<super::permissions::Entity>,
    #[sea_orm(
        belongs_to,
        from = "realm_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub realms: HasOne<super::realms::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
