//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "trip_cards")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub trip_id: Uuid,
    pub created_by: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub category: Option<String>,
    pub start_time: Option<DateTimeWithTimeZone>,
    pub end_time: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub display_order: Option<i32>,
    pub vote_count: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub vote_data: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"geography\")",
        select_as = "text",
        nullable
    )]
    pub position: Option<String>,
    #[sea_orm(has_one)]
    pub trip_card_rich_text: HasOne<super::trip_card_rich_text::Entity>,
    #[sea_orm(
        belongs_to,
        from = "trip_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub trips: HasOne<super::trips::Entity>,
    #[sea_orm(has_many, via = "trip_card_votes")]
    pub profiles: HasMany<super::profiles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
