//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "trip_card_rich_text")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub trip_card_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub content: Json,
    pub last_edited_by: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::profiles::Entity",
        from = "Column::LastEditedBy",
        to = "super::profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Profiles,
    #[sea_orm(
        belongs_to = "super::trip_cards::Entity",
        from = "Column::TripCardId",
        to = "super::trip_cards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TripCards,
}

impl Related<super::profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profiles.def()
    }
}

impl Related<super::trip_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TripCards.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
