//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "trip_cards")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub trip_id: Uuid,
    pub created_by: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub category: Option<String>,
    pub start_time: Option<DateTimeWithTimeZone>,
    pub end_time: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub display_order: Option<i32>,
    pub vote_count: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub vote_data: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(
        ignore,
        column_type = "custom(\"geography\")",
        select_as = "text",
        nullable
    )]
    pub position: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::profiles::Entity",
        from = "Column::CreatedBy",
        to = "super::profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Profiles,
    #[sea_orm(has_one = "super::trip_card_rich_text::Entity")]
    TripCardRichText,
    #[sea_orm(has_many = "super::trip_card_votes::Entity")]
    TripCardVotes,
    #[sea_orm(
        belongs_to = "super::trips::Entity",
        from = "Column::TripId",
        to = "super::trips::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Trips,
}

impl Related<super::trip_card_rich_text::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TripCardRichText.def()
    }
}

impl Related<super::trip_card_votes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TripCardVotes.def()
    }
}

impl Related<super::trips::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trips.def()
    }
}

impl Related<super::profiles::Entity> for Entity {
    fn to() -> RelationDef {
        super::trip_card_votes::Relation::Profiles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::trip_card_votes::Relation::TripCards.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
