//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "trips")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub realm_id: Uuid,
    pub created_by: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub destination: Option<String>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(has_one)]
    pub chats: HasOne<super::chats::Entity>,
    #[sea_orm(
        belongs_to,
        from = "realm_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub realms: HasOne<super::realms::Entity>,
    #[sea_orm(has_many)]
    pub trip_cards: HasMany<super::trip_cards::Entity>,
    #[sea_orm(has_many, via = "trip_participants")]
    pub profiles: HasMany<super::profiles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
