//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "trips")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub realm_id: Uuid,
    pub created_by: Uuid,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub destination: Option<String>,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::chats::Entity")]
    Chats,
    #[sea_orm(
        belongs_to = "super::profiles::Entity",
        from = "Column::CreatedBy",
        to = "super::profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Profiles,
    #[sea_orm(
        belongs_to = "super::realms::Entity",
        from = "Column::RealmId",
        to = "super::realms::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Realms,
    #[sea_orm(has_many = "super::trip_cards::Entity")]
    TripCards,
    #[sea_orm(has_many = "super::trip_participants::Entity")]
    TripParticipants,
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chats.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::trip_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TripCards.def()
    }
}

impl Related<super::trip_participants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TripParticipants.def()
    }
}

impl Related<super::profiles::Entity> for Entity {
    fn to() -> RelationDef {
        super::trip_participants::Relation::Profiles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::trip_participants::Relation::Trips.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
